name: Sword
version: 0.2.0
category: Language

ghc-options:
  - -Wall
  - -Wnoncanonical-monad-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base
  - mtl
  - parsec
  - text
  - bytestring
  - containers
  - cryptonite
  - aeson
  - split
  - directory
  - optparse-applicative
  - filepath

library:
  source-dirs: src

executables:
  swordc: &swordc
    main: src/Main.hs
    dependencies:
      - Sword

tests:
  unit:
    source-dirs: test
    main: main_tests.hs
    dependencies:
      - Sword
      - HUnit
      - hspec
      - QuickCheck