name: Sword
version: 0.2.0
category: Language

ghc-options:
  - -Wall
  - -Wnoncanonical-monad-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - base >= 4.9.1.0
    - mtl
    - parsec
    - text
    - bytestring >= 0.10.8.1
    - containers >= 0.5.7.1
    - cryptonite >= 0.21
    - aeson >= 1.0.2.1
    - split >= 0.2.3.1
    - directory >= 1.3.0.0

executables:
  daggerc: &daggerc
    main: src/Main.hs
    dependencies:
      - Sword
      - base >= 4.9.1.0
      - aeson >= 1.0.2.1
      - bytestring >= 0.10.8.1
      - split >= 0.2.3.1
      - directory >= 1.3.0.0
  # daggerfmt: &dagger
  #   source-dirs: unittests
  #   main: DaggerFmt.hs
  #   dependencies:
  #     - daggerc
  #     - base >= 4.9.1.0
  #     - HUnit
  #     - QuickCheck
  #     - containers
  #     - hspec
  #     - mtl

tests:
  unit:
    source-dirs: unittests
    main: main_tests.hs
    dependencies:
      - Sword
      - base >= 4.9.1.0
      - HUnit
      - QuickCheck
      - containers
      - hspec
      - mtl
